parameters:
  - name: group
    type: string
    default: 'rg-azappsvc-1'
  - name: webappname
    type: string
  - name: deployCondition
    type: boolean
  - name: ArtifactName
    type: string

stages:
  - stage: Deploy_${{replace(parameters.webappname,'-','_')}}
    condition: and(succeeded(), eq('true','${{parameters.deployCondition}}'))
    jobs:
      - job: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DownloadPipelineArtifact@0
            name: Download_Artifacts
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)
              artifact: ${{ parameters.ArtifactName }}